name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message for you
          run: echo "My first github actions workflow"

        - name: list files
          run: ls

        - name: read file
          run: cat main.yml
